name: itp107_assessment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Nasa assets folder lahat ng fonts, icons, images lalagay nyo dito lahat ng assets
  # para marecognize ng flutter.
  # If image lagay lang kayo image sa images folder then type nyo dito. same thing lang din
  # with other assets.
  # fonts link: https://fonts.google.com/
  assets:
    - assets/images/booksample.webp

  fonts:
   - family: Roboto
     fonts: 
      - asset: assets/fonts/Roboto-Regular.ttf
     
      - asset: assets/fonts/Roboto-SemiBold.ttf
        weight: 400

      - asset: assets/fonts/Roboto-ExtraBold.ttf
        weight: 700
